#!/usr/bin/env bash
# Author: Andre Rampono
# Student: 23840638

#### FUNCTION BEGINS
# Top level script
# From the given data file, calculates the mean correlation between predictors and the Cantril ladder score.
# Outputs the mean scores and as well the mean score with the greatest absolute value.
# ARGUMENTS:
#   $1: tsv data file
# OUTPUTS
#   STDOUT: mean correlation for each predictor
#           predictor with greatest absolute value
#   STDERR:
#   RETURNS:
### FUNCTION END

# check CLI for valid number of arguments
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <tsv datafile> <tsv datafile> <tsv datafile>." > /dev/stderr
	exit 1
fi

# check the file contains data
for arg in "$@"; do
if [[ ! -s $arg ]]; then
	echo "Error: The file $arg does not exist or is not readable." > /dev/stderr
        exit 1
	fi
done

# delete header. causes issue with data processing 
tail -n +2 $1 | grep -v '^[[:space:]]*$' > _tmp_noHeader 

# delete blank lines
awk -F'\t' 'BEGIN {OFS=FS} ($4 == "" || $5 == "" || $6 == "" || $7 == "") || $8 == "" {next;} {print $0}' _tmp_noHeader > _tmp_predictorData

# generate standard deviation calculation for each predictor
awk -f gdp_calcpredictor.awk _tmp_predictorData > _check_allCalc
awk -f popltn_calcpredictor.awk _tmp_predictorData >> _check_allCalc
awk -f h_calcpredictor.awk _tmp_predictorData >> _check_allCalc
awk -f life_calcpredictor.awk _tmp_predictorData >> _check_allCalc

awk -f all_calcpredictor.awk _check_allCalc

# clean up temp files
rm ./_*
