#!/usr/bin/env bash
# Author: Andre Rampono
# Student: 23840638

#### FUNCTION BEGINS
# Given three tsv data files, clean each file for a date range (2011-2021),
# remove the Continent column from GDP and Life files as well as rows
# that do not contain a Code for the associated Entity column
# Format of results depends on $2 input
# ARGUMENTS:
#   $1: tsv data file
#   $2: tsv data file
#   $3: tsv data file
# OUTPUTS
#   STDOUT: the cleaned data of the three input files combined from selected columns
#           to derive the best predictor of Cantril-ladder life-satisfaction scores.
#   STDERR: All errors
### FUNCTION END


# Check CLI for valid number of arguments
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <tsv datafile> <tsv datafile> <tsv datafile>." > /dev/stderr
	exit 1
fi

# Check the file contains data
for arg in "$@"; do
if [[ ! -s $arg ]]; then
	echo "Error: The file $arg does not exist or is not readable." > /dev/stderr
        exit 1
	fi
done

# delete header. causes issue with data processing
# delete blank lines - 
tail -n +2 $1 | grep -v '^[[:space:]]*$' > _tmp_noHeader 

# Delete the header
awk -F'\t' 'BEGIN {OFS=FS} ($4 == "" || $5 == "" || $6 == "" || $7 == "") || $8 == "" {next;} {print $0}' _tmp_noHeader > _tmp_predictorData

# generate standard deviation calculation for each predictor
awk -f gdp_calcpredictor.awk _tmp_predictorData > _check_gdpCalc
awk -f popltn_calcpredictor.awk _tmp_predictorData > _check_popltnCalc
awk -f h_calcpredictor.awk _tmp_predictorData > _check_homicideCalc
awk -f life_calcpredictor.awk _tmp_predictorData > _check_lifeCalc

gpd_mean=$(cat _check_gdpCalc)
echo $gdp_mean


#TODO REMOVE TEMP FILES
# clean up temp files
#rm ./_*
