#!/usr/bin/env bash
#set -x
#for arg in "$@"
#do
#    fields=$(head -n1 $arg | awk -F'\t' '{print NF;exit}')
#    num_col=$(($fields+1))
#    echo $num_col
#
#    awk 'BEGIN {FS="\t"} NR==FNR {arr1[NR]=$0; next} NR==FNR+num1 {arr2[NR]=$0; next} {print arr1[FNR], arr2[FNR], $0}' gdp-vs-happiness.tsv homicide-rate-unodc.tsv life-satisfaction-vs-life-expectancy.tsv> extract.tsv

#    awk -F'\t' '(int($3) < 2011 || int($3) > 2021) || $2 == ""{next;}{print $0}' $arg | sort -k1,1 -k3,3n | cut -f1-6 > "_$arg"
#done




for arg in "$@"
do
    sed -n '1p' $arg > header_extract.tsv
    if grep -E -q [Ll]ife header_extract.tsv
    then
        echo In "$arg"
        awk -F'\t' '(int($3) < 2011 || int($3) > 2021) || $2 == ""{next;}{print $0}' $arg | sort -k1,1 -k3,3n | cut -f1-6 > "_life"
    elif grep -q GDP header_extract.tsv
    then
        echo In "$arg"
        awk -F'\t' '(int($3) < 2011 || int($3) > 2021) || $2 == ""{next;}{print $0}' $arg | sort -k1,1 -k3,3n | cut -f1-6 > "_gdp"
    elif grep -q Homicide header_extract.tsv
    then
        echo In "$arg"
        awk -F'\t' '(int($3) < 2011 || int($3) > 2021) || $2 == ""{next;}{print $0}' $arg | sort -k1,1 -k3,3n | cut -f1-4 > "_homicide"
    fi
done



    #if grep -q "life" $col_header 
    #then
    #    echo In "$arg"
    #elif grep -q "gdp" $col_header
    #then
    #    echo In "$arg"
    #elif grep -q "homicide" $col_header
    #then
    #    echo In "$arg"
    #fi
#:done

T=$(printf '\t')
entity=$(printf "Entity")
code=$(printf "Code")
year=$(printf "Year")
gdp=$(printf "GDP per capita")
popln=$(printf "Population")
homicide=$(printf "Homicide Rate")
life=$(printf "Life Expectancy")
cantril=$(printf "Cantril Ladder Score")

#awk 'NR==FNR{array[$1]=$3FS$4FS$5FS$6FS$7FS$8; next} { print $0,array[$1]}' file2 file1

#echo "Entity Code \t Year \t GDP per capita\t Population \t Homicide \t Life expectancy \t Cantril ladder score" > final_extract.txt


#awk -F, 'NR==FNR{a[$1]=$2;b[$1]=next}
#{if ($2 in a){$3=$2;$4=a[$2];delete a[$2];}}1' OFS="\t" _gdp-vs-happiness.tsv _homicide-rate-unodc.tsv _life-satisfaction-vs-life-expectancy.tsv
#awk 'BEGIN{FS=","} NR==1{print;next} {a[$2][$3]=$2 in a ? a[$2] " " $1 : $1} END{for(i in a) print a[i] "," i}'
